name: Funscript Generator (FunGen)
description: Generate funscripts for Stash scenes using the FunGen CLI.
version: 0.1.5
exec:
  - python3
  - "{pluginDir}/fungen_stash_plugin.py"
interface: raw
errLog: info

settings:
  - name: FunGen repo URL
    key: fungen_repo
    type: string
    default: ""
    description: Git URL for the FunGen repo (used by Install FunGen CLI).
  - name: FunGen repo ref
    key: fungen_ref
    type: string
    default: ""
    description: Optional branch, tag, or commit for the FunGen repo.
  - name: FunGen path
    key: fungen_path
    type: string
    default: "{pluginDir}/fungen/main.py"
    description: Path to FunGen entrypoint (main.py) on the Stash host.
  - name: Python path
    key: python_path
    type: string
    default: python3
    description: Python executable to use when running FunGen.

tasks:
  - name: Install FunGen CLI
    description: Clones or updates the FunGen repo into the plugin directory.
    defaultArgs:
      scope: install
      install_dir: "{pluginDir}/fungen"
      fungen_repo: ""
      fungen_ref: ""

  - name: Generate funscripts for all scenes
    description: Runs FunGen for every scene in the library and skips existing .funscript files.
    defaultArgs:
      scope: all
      host: localhost
      python_path: python3
      fungen_path: "{pluginDir}/fungen/main.py"
      mode: ""
      od_mode: current
      overwrite: false
      no_autotune: false
      no_copy: false
      extra_args: ""

hooks:
  - name: Auto-generate funscript on scene import
    description: Runs FunGen when a new scene is created.
    triggeredBy:
      - Scene.Create.Post
    defaultArgs:
      scope: hook
      host: localhost
      python_path: python3
      fungen_path: "{pluginDir}/fungen/main.py"
      mode: ""
      od_mode: current
      overwrite: false
      no_autotune: false
      no_copy: false
      extra_args: ""
