name: Funscript Generator (FunGen)
description: Generate funscripts for Stash scenes using the FunGen CLI.
version: 0.1.7
exec:
  - python3
  - "{pluginDir}/fungen_stash_plugin.py"
interface: raw
errLog: info

settings:
  fungen_repo:
    type: string
    displayName: FunGen repo URL
    description: Git URL for the FunGen repo (used by Install FunGen CLI).
  fungen_ref:
    type: string
    displayName: FunGen repo ref
    description: Optional branch, tag, or commit for the FunGen repo.
  fungen_path:
    type: string
    displayName: FunGen path
    description: Path to FunGen entrypoint (main.py) on the Stash host.
  python_path:
    type: string
    displayName: Python path
    description: Python executable to use when running FunGen.

tasks:
  - name: Install FunGen CLI
    description: Clones or updates the FunGen repo into the plugin directory.
    defaultArgs:
      scope: install
      install_dir: "{pluginDir}/fungen"
      fungen_repo: ""
      fungen_ref: ""

  - name: Generate funscripts for all scenes
    description: Runs FunGen for every scene in the library and skips existing .funscript files.
    defaultArgs:
      scope: all
      host: localhost
      python_path: python3
      fungen_path: "{pluginDir}/fungen/main.py"
      mode: ""
      od_mode: current
      overwrite: false
      no_autotune: false
      no_copy: false
      extra_args: ""

hooks:
  - name: Auto-generate funscript on scene import
    description: Runs FunGen when a new scene is created.
    triggeredBy:
      - Scene.Create.Post
    defaultArgs:
      scope: hook
      host: localhost
      python_path: python3
      fungen_path: "{pluginDir}/fungen/main.py"
      mode: ""
      od_mode: current
      overwrite: false
      no_autotune: false
      no_copy: false
      extra_args: ""
